draw_set_halign(fa_left)
draw_set_valign(fa_top)
draw_set_color(c_white)
draw_rectangle(x, y, x+width, y+height, false)

draw_set_color(c_black)
draw_rectangle(x, y, x+width, y+height, true)
draw_set_font(fnt_text)
draw_set_halign(fa_center)
draw_text(x+padding + width/2, y+padding, text)