name = "Placa de 4 poços"
xx = 0
yy = 0
base_x = x 
base_y = y
options = []
needed_EPI = [obj_glove,obj_lab_coat, obj_goggles]
scale_on_contact_list = []
tool_tip = noone
on_release = undefined
drag_mode = false;
locked = false
scale_pulse_data = undefined
default_depth = depth
esmalte = 0
dentina = 0
acidulado = 0
neutro = 0
