name = "Não Setado"
xx = 0
yy = 0
base_x = x 
base_y = y
options = []
needed_EPI = []
scale_on_contact_list = []
tool_tip = noone
on_release = undefined
drag_mode = false;
locked = false
scale_pulse_data = undefined